Repository wecode-bootcamp-korea/41-2nd-BossBaby-backend, pull requests merged in 2023-02, with the labels that each got.

#3 [ADD] migration files
  .gitignore
  db/migrations/20230131120542_create_users_table.sql
  db/migrations/20230131120558_create_sellers_table.sql
  db/migrations/20230131120608_create_conditions_table.sql
  db/migrations/20230131120615_create_main_categories_table.sql
  db/migrations/20230131120624_create_sub_categories_table.sql
  db/migrations/20230131120634_create_order_status_table.sql
  db/migrations/20230131120646_create_products_table.sql
  db/migrations/20230131120652_create_likes_table.sql
  db/migrations/20230131120704_create_reviews_table.sql
  db/migrations/20230131120716_create_review_images_table.sql
  db/migrations/20230131120728_create_product_images_table.sql
  db/migrations/20230131120735_create_orders_table.sql
Labels: 멘토 리뷰 요청

#4 [ADD] 초기 세팅 패키지 추가 설치 및 healthCheck test code 추가
  .env.sample
  .env.test
  api/utils/error.js
  package-lock.json
  package.json
  test/healthCheck.test.js
Labels: 멘토 리뷰 요청, 리뷰 진행 중

#5 [ADD] 카카오 회원가입, 로그인 구현
  .env.sample
  .env.test
  .gitignore
  api/controllers/userController.js
  api/middlewares/error.js
  api/models/userDao.js
  api/routes/index.js
  api/routes/userRouter.js
  api/services/userService.js
  api/utils/detectError.js
  db/migrations/20230131120542_create_users_table.sql
  db/migrations/20230131120716_create_review_images_table.sql
  package-lock.json
  package.json
Labels: 멘토 리뷰 요청

#11 [MODIFY] db_migration 수정
  db/migrations/20230131120542_create_users_table.sql
  db/migrations/20230131120558_create_sellers_table.sql
  db/migrations/20230131120646_create_products_table.sql
  db/migrations/20230131120652_create_likes_table.sql
  db/migrations/20230131120704_create_reviews_table.sql
  db/migrations/20230131120716_create_review_images_table.sql
  db/migrations/20230131120728_create_product_images_table.sql
  db/migrations/20230207120130_create_product_status_table.sql
Labels: 멘토 리뷰 요청

#9 [ADD] orders 기능 구현
  api/controllers/orderController.js
  api/controllers/userController.js
  api/models/appDataSource.js
  api/models/orderDao.js
  api/models/userDao.js
  api/routes/index.js
  api/routes/orderRouter.js
  api/routes/userRouter.js
  api/services/orderService.js
  api/services/userService.js
  api/utils/auth.js
  api/utils/error.js
Labels: 멘토 리뷰 요청

#14 [FIX] 카카오 회원가입 코드
  api/middlewares/error.js
  api/models/userDao.js
  api/routes/index.js
  api/services/userService.js
Labels: 멘토 리뷰 요청

#15 [Fix] points 예외처리 코드
  api/controllers/orderController.js
  api/models/orderDao.js
  api/models/userDao.js
  api/routes/index.js
  api/services/orderService.js
  api/services/userService.js
  api/utils/auth.js
Labels: 멘토 리뷰 요청

#12 [ADD] feature/product 상품 관련 페이지 기능 추가
  api/controllers/productController.js
  api/controllers/userController.js
  api/models/appDataSource.js
  api/models/productDao.js
  api/models/userDao.js
  api/routes/index.js
  api/routes/productRouter.js
  api/routes/userRouter.js
  api/services/productService.js
  api/services/userService.js
  api/utils/enum.js
  app.js
  package-lock.json
  package.json
Labels: 완료
